CC = g++
CFLAGS = -Wall
SCHEMAS = schema_1, schema_2, schema_3, schema_4, schema_5, schema_6

schema_1: 
	$(CC) $(CFLAGS) -o schema_1 ./schema1/main1.cpp

schema_2: 
	$(CC) $(CFLAGS) -o schema_2 ./schema2/main2.cpp

schema_3: 
	$(CC) $(CFLAGS) -o schema_3 ./schema3/main3.cpp

schema_4: 
	$(CC) $(CFLAGS) -o schema_4 ./schema4/main4.cpp

schema_5: 
	$(CC) $(CFLAGS) -o schema_5 ./schema5/main5.cpp

schema_6: 
	$(CC) $(CFLAGS) -o schema_6 ./schema6/main6.cpp

clean:
	rm -f schema_1 schema_2 schema_3 schema_4 schema_5 schema_6
